### PR TITLE
slightly different json structure for results

### PR DESCRIPTION
**Pull request by gbordyugov**
as requested by backend

### CODE REVIEW

**Comment by gbordyugov** [comment]
An example of output:
```
{
  "warnings": [
    "kpi: normal_unequal_variance, variant: A: Sample variances differ too much to assume that population variances are equal."
  ],
  "errors": [],
  "expan_version": "0.6.0",
  "control_variant": "B",
  "kpis": [
    {
      "name": "normal_unequal_variance",
      "variants": [
        {
          "name": "B",
          "delta_statistics": {
            "delta": 0.0,
            "interval": [
              {
                "percentile": 2.5,
                "value": -0.446001163947657
              },
              {
                "percentile": 97.5,
                "value": 0.4460011639476569
              }
            ],
            "n_x": 3892,
            "n_y": 3892,
            "mu_x": 0.003037663356943815,
            "mu_y": 0.003037663356943815
          }
        },
        {
          "name": "A",
          "delta_statistics": {
            "delta": -0.01841022839936287,
            "interval": [
              {
                "percentile": 2.5,
                "value": -0.2720932120992578
              },
              {
                "percentile": 97.5,
                "value": 0.23527275530053202
              }
            ],
            "n_x": 6108,
            "n_y": 3892,
            "mu_x": -0.015372565042419054,
            "mu_y": 0.003037663356943815
          }
        }
      ]
    },
    {
      "name": "treatment_start_time",
      "variants": [
        {
          "name": "B",
          "delta_statistics": {
            "delta": 0.0,
            "interval": [
              {
                "percentile": 2.5,
                "value": -0.1277613548944237
              },
              {
                "percentile": 97.5,
                "value": 0.12776135489442367
              }
            ],
            "n_x": 3892,
            "n_y": 3892,
            "mu_x": 4.547019527235355,
            "mu_y": 4.547019527235355
          }
        },
        {
          "name": "A",
          "delta_statistics": {
            "delta": -0.045873489252381106,
            "interval": [
              {
                "percentile": 2.5,
                "value": -0.16243991524476273
              },
              {
                "percentile": 97.5,
                "value": 0.07069293674000049
              }
            ],
            "n_x": 6108,
            "n_y": 3892,
            "mu_x": 4.5011460379829735,
            "mu_y": 4.547019527235355
          }
        }
      ]
    },
    {
      "name": "normal_shifted_by_feature",
      "variants": [
        {
          "name": "B",
          "delta_statistics": {
            "delta": 0.0,
            "interval": [
              {
                "percentile": 2.5,
                "value": -0.04960461263007906
              },
              {
                "percentile": 97.5,
                "value": 0.04960461263007905
              }
            ],
            "n_x": 3892,
            "n_y": 3892,
            "mu_x": 0.4787468949998453,
            "mu_y": 0.4787468949998453
          }
        },
        {
          "name": "A",
          "delta_statistics": {
            "delta": -0.46228190430127086,
            "interval": [
              {
                "percentile": 2.5,
                "value": -0.5041603198518145
              },
              {
                "percentile": 97.5,
                "value": -0.4204034887507272
              }
            ],
            "n_x": 6108,
            "n_y": 3892,
            "mu_x": 0.01646499069857442,
            "mu_y": 0.4787468949998453
          }
        }
      ]
    },
    {
      "name": "normal_shifted",
      "variants": [
        {
          "name": "B",
          "delta_statistics": {
            "delta": 0.0,
            "interval": [
              {
                "percentile": 2.5,
                "value": -0.04437869872180071
              },
              {
                "percentile": 97.5,
                "value": 0.0443786987218007
              }
            ],
            "n_x": 3892,
            "n_y": 3892,
            "mu_x": 0.985470421250268,
            "mu_y": 0.985470421250268
          }
        },
        {
          "name": "A",
          "delta_statistics": {
            "delta": -0.9909858530316658,
            "interval": [
              {
                "percentile": 2.5,
                "value": -1.0310019581408156
              },
              {
                "percentile": 97.5,
                "value": -0.9509697479225158
              }
            ],
            "n_x": 6108,
            "n_y": 3892,
            "mu_x": -0.005515431781397833,
            "mu_y": 0.985470421250268
          }
        }
      ]
    },
    {
      "name": "normal_same",
      "variants": [
        {
          "name": "B",
          "delta_statistics": {
            "delta": 0.0,
            "interval": [
              {
                "percentile": 2.5,
                "value": -0.04423521027363357
              },
              {
                "percentile": 97.5,
                "value": 0.04423521027363356
              }
            ],
            "n_x": 3892,
            "n_y": 3892,
            "mu_x": -0.007833095215783122,
            "mu_y": -0.007833095215783122
          }
        },
        {
          "name": "A",
          "delta_statistics": {
            "delta": 0.03305253940683865,
            "interval": [
              {
                "percentile": 2.5,
                "value": -0.007134748551444858
              },
              {
                "percentile": 97.5,
                "value": 0.07323982736512216
              }
            ],
            "n_x": 6108,
            "n_y": 3892,
            "mu_x": 0.025219444191055533,
            "mu_y": -0.007833095215783122
          }
        }
      ]
    }
  ]
}
```

Early stopping methods have an additional Boolean `stop` field in `delta_statistics`.

**Comment by mkolarek** [comment]
looks good, though where does "stop" go?

**Comment by gbordyugov** [comment]
An example of early stopping output:

```
{
  "warnings": [],
  "errors": [],
  "expan_version": "0.6.0",
  "control_variant": "B",
  "kpis": [
    {
      "name": "normal_same",
      "variants": [
        {
          "name": "B",
          "delta_statistics": {
            "stop": false,
            "delta": 0.0,
            "interval": [
              {
                "percentile": 2.5,
                "value": -0.04523197836054499
              },
              {
                "percentile": 97.5,
                "value": 0.04352304730660999
              }
            ],
            "n_x": 3892,
            "n_y": 3892,
            "mu_x": -0.007833095215783122,
            "mu_y": -0.007833095215783122,
            "num_iters": 25000
          }
        },
        {
          "name": "A",
          "delta_statistics": {
            "stop": false,
            "delta": 0.03305253940683865,
            "interval": [
              {
                "percentile": 2.5,
                "value": -0.006477329777969295
              },
              {
                "percentile": 97.5,
                "value": 0.07402051534378247
              }
            ],
            "n_x": 6108,
            "n_y": 3892,
            "mu_x": 0.025219444191055533,
            "mu_y": -0.007833095215783122,
            "num_iters": 25000
          }
        }
      ]
    }
  ]
}
```

**Review by mkolarek — APPROVED** [review]

**Review by shansfolder — APPROVED** [review]
Looks good!

**Pull request merged**
