### PR TITLE
refactor get_data_for_analysis

### PR DESCRIPTION
**Pull request by igusher**
My main goal is to change responsibilities a bit between classes in order to modularize computations so that later we can reuse some chunks in distributed environment. 

The first thing I want to do - is to encapsulate computational logic in StatisticalTest. As it will be a building block in distributed environment and one StatisticalTest can run independently from the other. (Of course later StatisticalTestSuite will collect all Tests and correct them)
....
And I will do it in baby-steps so that you can see if I break any existing assumptions.

### CODE REVIEW

**Comment by igusher** [comment]
Well, exactly this change is trying to improve code according to [Law of Demeter](https://hackernoon.com/object-oriented-tricks-2-law-of-demeter-4ecc9becad85)

**Comment by igusher** [comment]
I've changed classes which are derived from JsonSerializable.
Could it potentially break existing serialization ?

**Comment by daryadedik** [comment]
@igusher can it be reviewed or it's in progress?

**Comment by igusher** [comment]
@daryadedik  Yes, this one is ready for review.

**Comment by aaron-mcdaid-zalando** [comment]
This breaks very many of the `ExpanService` tests

The errors are usually something to do with serializing `weakref`:

````
AttributeError: 'weakref' object has no attribute '__dict__'
ERROR:ExpanService:'weakref' object has no attribute '__dict__'
````

**Comment by igusher** [comment]
@aaron-mcdaid-zalando What is an `ExpanService`? I'm not aware of it. I'm just a random contributor to an exapn lib :)
Do you know when and how it attempts to serialize weakrefs? which objects are those?

**Pull request closed without merging**
