### PR TITLE
new travis config specifying that only master and dev should be built

### PR DESCRIPTION
**Pull request by mkolarek**

### CODE REVIEW

**Comment by jbao** [comment]
so if one opens a new PR to merge a feature branch into dev, the feature branch will actually not be checked by Travis?

**Comment by mkolarek** [comment]
@jbao any pull request against dev or master will be checked by travis, while any tagged commit to master will be checked and deployed

**Comment by jbao** [comment]
that sounds good;-)

**Comment by robertmuil** [comment]
So can this be merged, despite the checks failing?

**Pull request merged**
