### PR TITLE
Updated intro documentation covering delta methods.

### PR DESCRIPTION
**Pull request by daryadedik**
Updated .ipynb and generated new .html file.

### CODE REVIEW

**Comment by gbordyugov** [comment]
Looks great, but that's exactly the problem with this kind of documentation: it changes a lot (styles, formatting, etc.) after small changes.

In the future we have to think of a better alternative.

**Comment by daryadedik** [comment]
AFAIK, in R there is an automated documentation file generation process, you don't need to do formatting you just change fields (name of function, what it does, what parameters it accepts) and create examples and build it (very similar to latex format). Don't know whether there is something like that in Python.

**Comment by shansfolder** [comment]
That's the documentation generated by Sphinx we had in the /docs folder. It can read doc strings and build an api doc, but we are not using it. We should definitely plan for a ticket to have better documentations (not the quick fix we have right now).

**Comment by shansfolder** [comment]
and for the current PR, I have two quick comments:
1. Can you move the section for parameters of deltas up, before the section of interpreting results?
2. Regarding the fields in ```metadata```, I actually meant removing only ```baseline_variant``` (and keep the others as optional, maybe only ```experiment``` as mandatory) because in the example we have more:
```
{'experiment': 'random_data_generation',
 'primary_KPI': 'normal_shifted',
 'source': 'simulated'}
```

**Comment by daryadedik** [comment]
@shansfolder sure, will do the changes.

**Review by shansfolder — APPROVED** [review]

**Pull request merged**
