### PR TITLE
Changed structure for statistics without correction

### PR DESCRIPTION
**Pull request by daryadedik**
CombineTestStatistics for original and corrected statistics, corrected equals to original if no correction is done.

### CODE REVIEW

**Review by shansfolder — APPROVED** [review]
Looks good! I'll add some documentation.

**Comment by daryadedik** [comment]
@shansfolder thank you!

**Comment by daryadedik** [comment]
@sh @gbordyugov can I merge this pull request?

**Comment by shansfolder** [comment]
@daryadedik It looks good to me. :)

**Pull request merged**
